library chat_sdk_define;

import 'package:im_flutter_sdk/im_flutter_sdk.dart' as chat;
export 'package:im_flutter_sdk/im_flutter_sdk.dart';

typedef Client = chat.EMClient;
typedef ChatManager = chat.EMChatManager;
typedef ChatEventHandler = chat.EMChatEventHandler;
typedef GroupEventHandler = chat.EMGroupEventHandler;
typedef RoomEventHandler = chat.EMChatRoomEventHandler;
typedef ContactEventHandler = chat.EMContactEventHandler;
typedef ConnectionEventHandler = chat.EMConnectionEventHandler;
typedef MultiDeviceEventHandler = chat.EMMultiDeviceEventHandler;
typedef Message = chat.EMMessage;
typedef MessageStatus = chat.MessageStatus;
typedef MessageDirection = chat.MessageDirection;
typedef MessageReactionEvent = chat.EMMessageReactionEvent;
typedef ReactionOperate = chat.ReactionOperate;
typedef GroupMessageAck = chat.EMGroupMessageAck;
typedef GroupSharedFile = chat.EMGroupSharedFile;
typedef Group = chat.EMGroup;
typedef Contact = chat.EMContact;
typedef MultiDevicesEvent = chat.EMMultiDevicesEvent;
typedef ConversationType = chat.EMConversationType;
typedef MessageEvent = chat.ChatMessageEvent;
typedef ChatError = chat.EMError;
typedef Conversation = chat.EMConversation;
typedef CursorResult<T> = chat.EMCursorResult<T>;
typedef MessageReaction = chat.EMMessageReaction;
typedef TranslateLanguage = chat.EMTranslateLanguage;
typedef TextMessageBody = chat.EMTextMessageBody;
typedef ImageMessageBody = chat.EMImageMessageBody;
typedef VoiceMessageBody = chat.EMVoiceMessageBody;
typedef FileMessageBody = chat.EMFileMessageBody;
typedef VideoMessageBody = chat.EMVideoMessageBody;
typedef LocationMessageBody = chat.EMLocationMessageBody;
typedef DownloadStatus = chat.DownloadStatus;
typedef CustomMessageBody = chat.EMCustomMessageBody;
typedef CombineMessageBody = chat.EMCombineMessageBody;
typedef CmdMessageBody = chat.EMCmdMessageBody;
typedef GroupInfo = chat.EMGroupInfo;
typedef GroupOptions = chat.EMGroupOptions;
typedef Options = chat.EMOptions;
typedef PushConfigs = chat.EMPushConfigs;
typedef DisplayStyle = chat.DisplayStyle;
typedef ChatSilentModeParam = chat.ChatSilentModeParam;
typedef ChatPushRemindType = chat.ChatPushRemindType;
typedef ChatSilentModeResult = chat.ChatSilentModeResult;
typedef FetchMessageOptions = chat.FetchMessageOptions;
typedef SearchDirection = chat.EMSearchDirection;
typedef ChatType = chat.ChatType;
typedef MessageType = chat.MessageType;
typedef GroupStyle = chat.EMGroupStyle;
typedef PresenceEventHandler = chat.EMPresenceEventHandler;
typedef Presence = chat.EMPresence;
typedef GroupPermissionType = chat.EMGroupPermissionType;
typedef ChatThreadEventHandler = chat.EMChatThreadEventHandler;
typedef ChatThreadEvent = chat.EMChatThreadEvent;
typedef ChatThreadOperation = chat.EMChatThreadOperation;
typedef ChatThread = chat.EMChatThread;
typedef MessageSearchScope = chat.MessageSearchScope;
typedef UserInfo = chat.EMUserInfo;
typedef MessagePinOperation = chat.MessagePinOperation;
typedef MessagePinInfo = chat.MessagePinInfo;
typedef LoginExtensionInfo = chat.LoginExtensionInfo;

typedef ChatRoomEventHandler = chat.EMChatRoomEventHandler;
typedef LeaveReason = chat.LeaveReason;
typedef ChatRoom = chat.EMChatRoom;
typedef PageResult<T> = chat.EMPageResult<T>;

/*
import 'package:agora_chat_sdk/agora_chat_sdk.dart' as chat;
export 'package:agora_chat_sdk/agora_chat_sdk.dart';

typedef Client = chat.ChatClient;
typedef ChatManager = chat.ChatManager;
typedef ChatEventHandle = chat.ChatEventHandler;
typedef GroupEventHandler = chat.ChatGroupEventHandler;
typedef RoomEventHandler = chat.ChatRoomEventHandler;
typedef ContactEventHandler = chat.ChatContactEventHandler;
typedef ConnectionEventHandler = chat.ConnectionEventHandler;
typedef MultiDeviceEventHandler = chat.ChatMultiDeviceEventHandler;
typedef Message = chat.ChatMessage;
typedef MessageStatus = chat.MessageStatus;
typedef MessageDirection = chat.MessageDirection;
typedef MessageReactionEvent = chat.ChatMessageReactionEvent;
typedef ReactionOperate = chat.ReactionOperate;
typedef GroupMessageAck = chat.ChatGroupMessageAck;
typedef GroupSharedFile = chat.ChatGroupSharedFile;
typedef Group = chat.ChatGroup;
typedef Contact = chat.ChatContact;
typedef MultiDevicesEvent = chat.ChatMultiDevicesEvent;
typedef ConversationType = chat.ChatConversationType;
typedef MessageEvent = chat.ChatMessageEvent;
typedef ChatError = chat.ChatError;
typedef Conversation = chat.ChatConversation;
typedef CursorResult<T> = chat.ChatCursorResult<T>;
typedef MessageReaction = chat.ChatMessageReaction;
typedef TranslateLanguage = chat.ChatTranslateLanguage;
typedef TextMessageBody = chat.ChatTextMessageBody;
typedef ImageMessageBody = chat.ChatImageMessageBody;
typedef VoiceMessageBody = chat.ChatVoiceMessageBody;
typedef FileMessageBody = chat.ChatFileMessageBody;
typedef VideoMessageBody = chat.ChatVideoMessageBody;
typedef LocationMessageBody = chat.ChatLocationMessageBody;
typedef DownloadStatus = chat.DownloadStatus;
typedef CustomMessageBody = chat.ChatCustomMessageBody;
typedef CombineMessageBody = chat.CombineMessageBody;
typedef CmdMessageBody = chat.ChatCmdMessageBody;
typedef GroupInfo = chat.ChatGroupInfo;
typedef GroupOptions = chat.ChatGroupOptions;
typedef Options = chat.ChatOptions;
typedef PushConfigs = chat.ChatPushConfigs;
typedef DisplayStyle = chat.DisplayStyle;
typedef ChatSilentModeParam = chat.ChatSilentModeParam;
typedef ChatPushRemindType = chat.ChatPushRemindType;
typedef ChatSilentModeResult = chat.ChatSilentModeResult;
typedef FetchMessageOptions = chat.FetchMessageOptions;
typedef SearchDirection = chat.ChatSearchDirection;
typedef ChatType = chat.ChatType;
typedef MessageType = chat.MessageType;
typedef GroupStyle = chat.ChatGroupStyle;
typedef PresenceEventHandler = chat.ChatPresenceEventHandler;
typedef Presence = chat.ChatPresence;
typedef GroupPermissionType = chat.ChatGroupPermissionType;
typedef ChatThreadEventHandler = chat.ChatThreadEventHandler;
typedef ChatThreadEvent = chat.ChatThreadEvent;
typedef ChatThreadOperation = chat.ChatThreadOperation;
typedef ChatThread = chat.ChatThread;
typedef MessageSearchScope = chat.MessageSearchScope;
typedef UserInfo = chat.ChatUserInfo;
typedef MessagePinOperation = chat.MessagePinOperation;
typedef MessagePinInfo = chat.MessagePinInfo;
// 1.3.1  开放
// typedef LoginExtensionInfo = chat.LoginExtensionInfo;

typedef ChatRoomEventHandler = chat.ChatRoomEventHandler;
typedef LeaveReason = chat.LeaveReason;
typedef ChatRoom = chat.ChatRoom;
typedef PageResult<T> = chat.ChatPageResult<T>;

*/
